Tugas1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crowd_funding.urls')),
    path('donasi/', include('app_donasi.urls')),
    path('formulir_donasi/', include('app_formulir_donasi.urls')),
    path('berita/', include('app_berita.urls')),
    path('pendaftaran_donatur/', include('app_pendaftaran_donatur.urls')),
    path('login/', include('app_login.urls')),
    path('testimoni/', include('app_testimoni.urls')),
]

app_donasi/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'programs'

urlpatterns = [
    path('', views.list_program, name='list_program'),
    path('<str:program>/', views.list_donatur, name='list_donatur'),
]

app_donasi/models.py
from django.db import models
from app_formulir_donasi.models import Donasi

# Create your models here.
class Program(models.Model):
    status = models.CharField(max_length=100)
    name   = models.CharField(max_length=200)
    photo  = models.ImageField(upload_to="static/img")
    desc   = models.TextField()
    target = models.IntegerField()
    remDay = models.IntegerField()
    donatur = models.ManyToManyField(Donasi)

app_donasi/views.py
from django.shortcuts import render, redirect
from .models import Program

# Create your views here.

def list_program(request):
    programs = Program.objects.all()
    response = {'programs': programs}
    return render(request, 'donasi.html', response)


def list_donatur(request, program):
    donasi_terkumpul = Program.objects.get(pk=program)
    nama_program = Program.objects.get(pk=program).name
    response = {
        'donasi_terkumpul': donasi_terkumpul,
        'nama_program' : nama_program,
        }
    return render(request, 'list_donatur.html', response)

app_donasi/templates/donasi.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- HEADER -->
    <header class="masthead container-fluid h-50">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="mx-auto text-center">
                <h1 class="text-white mx-auto my-0"><strong>Donasi</strong></h1>
            </div>
        </div>
    </header>

    <!-- DONASI -->
    <div class="container-fluid">
        <div class="row content">
			{% if programs %}
            {% for program in programs %}
            <div class="col-sm-4">
                <div class="roundedrec">
                    <img class="donasiimg" src="/{{ program.photo }}" style="width:100%">
                    <div class="insiderec">
                        <p class="judul"> {{ program.status }}</p>
                        <h4 class="w3-left-align" style="color: #F56462">{{ program.name }}</h4>
                        <p class="w3-left-align isi">{{ program.desc }}</p>
                        <p class="icon">
							<img src="{% static 'img/flag.png' %}">
							Target Rp {{ program.target }}
                        </p>
                        <p class="icon" style="padding-bottom: 20px;">
							<img src="{% static 'img/cal.png' %}">
							Sisa {{ program.remDay }} hari
                        </p>
                        {% if user.is_authenticated %}
                            <div id="loggedin">
                                <div class="center">
                                    <a href="{% url 'formulir_donasi' program=program.pk %}" class="btn btn-dark round" style="margin-bottom: 15px;padding: 17px 50px;"><strong>DONASI SEKARANG</strong></a>
                                    <br>
                                    <a class="isi kembali" style="text-decoration: underline;" href="{% url 'programs:list_donatur' program=program.pk %}">List Donatur</a>
                                </div>
                            </div>
                        {% else %}
                            <div id= "notloggedin">
                                <div class="center">
                                    <a class="isi kembali" style="text-decoration: underline;" href="{% url 'login' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Login terlebih dahulu<br>untuk melakukan donasi!</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
			{% endfor %}
            {% else %}
            <div class="col-sm-12">
                <div class="roundedrec">
                    <div class="insiderec">
                        <h4 class="w3-left-align" style="color: #F56462"><strong>Tidak ada program.</strong></h4>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app_donasi/templates/list_donatur.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- FORMULIR DONASI -->
    <div class="container-fluid">
        <div class="row content">
            <div class="col-sm-12">
                <div class="roundedrec">
                    <div class="insiderec">
                        <h1 class="text-center mx-auto my-0" style="padding-top: 10px; padding-bottom: 2rem; font-size: 45px; min-height: 50%;"><strong>Donasi Terkumpul</strong></h1>
                        <h4 class="text-center" style="color: #F56462; margin-top: -15px; margin-bottom: 3rem;"><strong>{{ nama_program }}</strong></h4>
                        <div class="main-div">
                            <div class="container mx-auto d-block">
                                {% if donasi_terkumpul.donatur.all.count == 0 %}
                                    <h3>Belum ada donasi terkumpul.</h3>
                                {% else %}
                                    <table class="table table-hover table-striped" align="center" style="text-align: center">
                                        <thead>
                                            <tr>
                                                <th scope="col">Nama Donatur</th>
                                                <th scope="col">Email</th>
                                                <th scope="col">Jumlah Donasi</th>
                                            </tr>
                                        </thead>
                                    {% for data in donasi_terkumpul.donatur.all %}
                                        {% if data == donasi_terkumpul.donatur.last %}
                                            <tr>
                                                <td scope="row">{{ data.nama }}</td>
                                                <td scope="row">{{ data.email }}</td>
                                                <td scope="row">{{ data.jmldonasi }}</td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td scope="row">{{ data.nama }}</td>
                                                <td scope="row">{{ data.email }}</td>
                                                <td scope="row">{{ data.jmldonasi }}</td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    </table>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                        <div class="kembali center">
                            <a class="isi kembali" style="text-decoration: underline;" href="{% url 'programs:list_program' %}">Kembali ke Halaman Sebelumnya</a>
                        </div>
                        <br>
                        <br>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}